version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3569:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
     # Fix shared memory issues for NeMo diarization
    shm_size: '2g'  # Increase shared memory to 2GB
    # Alternative approach - mount larger /dev/shm
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 600s
